truncate table STATUS;
insert into STATUS(ID,NAME) values(0,'ожидает');
insert into STATUS(ID,NAME) values(1,'забрали');
insert into STATUS(ID,NAME) values(2,'вернули');
insert into STATUS(ID,NAME) values(3,'отказали');
insert into STATUS(ID,NAME) values(4,'отказались');
insert into STATUS(ID,NAME) values(5,'перезвонить');
insert into STATUS(ID,NAME) values(6,'пропущен');
insert into STATUS(ID,NAME) values(7,'купили');
insert into STATUS(ID,NAME) values(8,'дубль');

insert into MODELS (ID, COMMENT, NAME, `TYPE`, PHOTO1, PHOTO2, PHOTO3, VIDEO1, VIDEO2, VIDEO3, DESCRIPTION1, DESCRIPTION2, DESCRIPTION3, CREATED)
select 4,'fresh&black','Arpenaz 3XL', `TYPE`, PHOTO1, PHOTO2, PHOTO3, VIDEO1, VIDEO2, VIDEO3, DESCRIPTION1, DESCRIPTION2, DESCRIPTION3, CURRENT_TIMESTAMP() 
FROM prokatparu_crm.MODELS where ID =3;

ALTER TABLE ORDERS MODIFY COLUMN GIVER_ID INT NULL, MODIFY COLUMN TAKER_ID INT NULL, MODIFY COLUMN GIVE_STOCK_ID INT NULL, MODIFY COLUMN TAKE_STOCK_ID INT NULL;

INSERT INTO STOCKS values(0,'виртуальный','не выбран',now(),'виртуальный склад - для заказов, где не выбран склад')
-- из-за autoincrement 0 не вставился
UPDATE STOCKS set id=0 WHEre id=5;

ALTER TABLE EMPLOYEES MODIFY COLUMN PHONE1 varchar(255) NULL, MODIFY COLUMN PHONE2 varchar(255) NULL, MODIFY COLUMN PHONE3 varchar(255) NULL;
INSERT INTO EMPLOYEES(ID,COMMENT, NAME, PHONE1 ,PHONE2, PHONE3 , CREATED, LOGIN , PASSWORD , STATUS)  values(0,'виртуальный сотрудник - для заказов, где не выбран сотрудник','не выбран',null,null,null,now(),'не выбран','несуществующий hash пароля, чтобы невозможно было под ним логиниться', 'работает')

ALTER TABLE ORDERS MODIFY COLUMN GIVER_ID int NOT NULL, MODIFY COLUMN TAKER_ID int NOT NULL, MODIFY COLUMN GIVE_STOCK_ID int NOT NULL, MODIFY COLUMN TAKE_STOCK_ID int NOT NULL;

ALTER TABLE ORDERS ADD COLUMN CHANNEL_ID int NOT NULL COMMENT 'откуда поступил заказ - от этого зависит цена';
UPDATE ORDERS SET CHANNEL_ID=1;
ALTER TABLE ORDERS  ADD CONSTRAINT FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNELS(ID);

ALTER TABLE prokatparu_crm.MODELS_TO_ORDERS DROP FOREIGN KEY MODELS_TO_ORDERS_ibfk_1;
ALTER TABLE prokatparu_crm.MODELS_TO_ORDERS ADD CONSTRAINT MODELS_TO_ORDERS_ibfk_1 FOREIGN KEY (MODEL_ID) REFERENCES prokatparu_crm.MODELS(ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE prokatparu_crm.MODELS_TO_ORDERS DROP FOREIGN KEY MODELS_TO_ORDERS_ibfk_2;
ALTER TABLE prokatparu_crm.MODELS_TO_ORDERS ADD CONSTRAINT MODELS_TO_ORDERS_ibfk_2 FOREIGN KEY (ORDER_ID) REFERENCES prokatparu_crm.ORDERS(ID) ON DELETE CASCADE ON UPDATE CASCADE;
