SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `CLIENTS`;
DROP TABLE IF EXISTS `EMPLOYEES`;
DROP TABLE IF EXISTS `STATUS`;
DROP TABLE IF EXISTS `STOCKS`;
DROP TABLE IF EXISTS `MODELS`;
DROP TABLE IF EXISTS `ITEMS`;
DROP TABLE IF EXISTS `ORDERS`;
DROP TABLE IF EXISTS `ITEMS_TO_ORDERS`;
DROP TABLE IF EXISTS `MODELS_TO_ORDERS`;
DROP TABLE IF EXISTS `MOVEMENTS`;
SET foreign_key_checks = 1;

SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `CLIENTS`;
CREATE TABLE `CLIENTS` (
  `ID` int(11) NOT NULL,
  `COMMENT` text,
  `NAME` varchar(255),
  `PHONE1` varchar(255) NOT NULL,
  `PHONE2` varchar(255),
  `PHONE3` varchar(255),
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DISCOUNT` float,
  `HISTORY` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `CLIENTS`  ADD PRIMARY KEY (`ID`);
ALTER TABLE `CLIENTS`  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;


DROP TABLE IF EXISTS `EMPLOYEES`;
CREATE TABLE `EMPLOYEES` (
  `ID` int(11) NOT NULL,
  `COMMENT` text,
  `NAME` varchar(255),
  `PHONE1` varchar(255) NOT NULL,
  `PHONE2` varchar(255),
  `PHONE3` varchar(255),
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LOGIN` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL COMMENT 'hash пароля',
  `STATUS` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `EMPLOYEES`  ADD PRIMARY KEY (`ID`);
ALTER TABLE `EMPLOYEES`  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
INSERT INTO `EMPLOYEES` (`PHONE1`, `NAME`, `LOGIN`, `PASSWORD`, `STATUS`) VALUES ('8916-345-77-25', 'Антон', 'anton', '12345', 'работает');


DROP TABLE IF EXISTS `STATUS`;
CREATE TABLE `STATUS` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(255) CHARACTER SET utf8 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `STATUS`  ADD PRIMARY KEY (`ID`);

insert into STATUS(ID,NAME) values(0,'ожидает');
insert into STATUS(ID,NAME) values(1,'забрали');
insert into STATUS(ID,NAME) values(2,'вернули');
insert into STATUS(ID,NAME) values(3,'отказали');
insert into STATUS(ID,NAME) values(4,'отказались');
insert into STATUS(ID,NAME) values(5,'перезвонить');
insert into STATUS(ID,NAME) values(6,'пропущен');
insert into STATUS(ID,NAME) values(7,'купили');
insert into STATUS(ID,NAME) values(8,'дубль');


DROP TABLE IF EXISTS `STOCKS`;
CREATE TABLE `STOCKS` (
  `ID` int(11) NOT NULL,
  `ADDRESS` varchar(1000) CHARACTER SET utf8 NOT NULL,
  `NAME` varchar(1000) CHARACTER SET utf8 NOT NULL,
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENT` varchar(1000) CHARACTER SET utf8 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Таблица складов';
ALTER TABLE `STOCKS`  ADD PRIMARY KEY (`ID`);
ALTER TABLE `STOCKS`  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;


INSERT INTO `STOCKS` (`ADDRESS`, `NAME`, `COMMENT`) VALUES ('Ленинградский проспект, 74к4', 'Сокол', 'Газель у Юниаструма');
INSERT INTO `STOCKS` (`ADDRESS`, `NAME`, `COMMENT`) VALUES ('Верхнелихоборская, 8а', 'Гараж', 'надпись на воротах 4А, гараж №8');
INSERT INTO `STOCKS` (`ADDRESS`, `NAME`, `COMMENT`) VALUES ('в прокате', 'в прокате', 'виртуальный склад - то, что находится у клиентов');


DROP TABLE IF EXISTS `MODELS`;
CREATE TABLE `MODELS` (
  `ID` int(11) NOT NULL,
  `COMMENT` varchar(255) CHARACTER SET utf8 NOT NULL,
  `NAME` varchar(255) CHARACTER SET utf8 NOT NULL,
  `TYPE` varchar(255) CHARACTER SET utf8 NOT NULL,
  `PHOTO1` varchar(255) CHARACTER SET utf8 NOT NULL,
  `PHOTO2` varchar(255) CHARACTER SET utf8 NOT NULL,
  `PHOTO3` varchar(255) CHARACTER SET utf8 NOT NULL,
  `VIDEO1` varchar(255) CHARACTER SET utf8 NOT NULL,
  `VIDEO2` varchar(255) CHARACTER SET utf8 NOT NULL,
  `VIDEO3` varchar(255) CHARACTER SET utf8 NOT NULL,
  `DESCRIPTION1` text CHARACTER SET utf8 NOT NULL,
  `DESCRIPTION2` text CHARACTER SET utf8 NOT NULL,
  `DESCRIPTION3` text CHARACTER SET utf8 NOT NULL,
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `MODELS`  ADD PRIMARY KEY (`ID`);
INSERT INTO `MODELS` (`ID`, `COMMENT`, `NAME`, `TYPE`, `PHOTO1`, `PHOTO2`, `PHOTO3`, `VIDEO1`, `VIDEO2`, `VIDEO3`, `DESCRIPTION1`, `DESCRIPTION2`, `DESCRIPTION3`, `CREATED`) VALUES (1, '', 'Quechua T4', 'палатка', 'http://prokat-palatok.ru/user/tovar//t8.jpg', '', '', '', '', '', 'Четырехместная туристическая палатка Quechua T4 - просторная кемпинговая палатка с большим тамбуром. Простая в установке и сделана из плотной ткани - надежно защитит от непогоды и поможет комфортно отдохнуть!', '', '', CURRENT_TIMESTAMP);
INSERT INTO `MODELS` (`ID`, `COMMENT`, `NAME`, `TYPE`, `PHOTO1`, `PHOTO2`, `PHOTO3`, `VIDEO1`, `VIDEO2`, `VIDEO3`, `DESCRIPTION1`, `DESCRIPTION2`, `DESCRIPTION3`, `CREATED`) VALUES (2, '', 'Green Glade Nida4', 'палатка', 'http://prokat-palatok.ru/user/tovar//t9.jpg', '', '', '', '', '', 'Синяя палатка', '', '', CURRENT_TIMESTAMP);
INSERT INTO `MODELS` (`ID`, `COMMENT`, `NAME`, `TYPE`, `PHOTO1`, `PHOTO2`, `PHOTO3`, `VIDEO1`, `VIDEO2`, `VIDEO3`, `DESCRIPTION1`, `DESCRIPTION2`, `DESCRIPTION3`, `CREATED`) VALUES (3, '', 'Спальник', 'спальный мешок', 'http://prokat-palatok.ru/user/tovar//t10.jpg', '', '', '', '', '', 'до +5С', '', '', CURRENT_TIMESTAMP);


DROP TABLE IF EXISTS `ITEMS`;
CREATE TABLE `ITEMS` (
  `ID` int(11) NOT NULL,
  `COMMENT` varchar(255) CHARACTER SET utf8 NOT NULL,
  `MODEL_ID` int(11) NOT NULL,
  `PHOTO1` varchar(255) CHARACTER SET utf8 NOT NULL,
  `PHOTO2` varchar(255) CHARACTER SET utf8 NOT NULL,
  `PHOTO3` varchar(255) CHARACTER SET utf8 NOT NULL,
  `STATUS` varchar(255) CHARACTER SET utf8 NOT NULL,
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `STOCK_ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `ITEMS`  ADD PRIMARY KEY (`ID`);
ALTER TABLE `ITEMS`  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
ALTER TABLE `ITEMS`  ADD CONSTRAINT FOREIGN KEY (MODEL_ID) REFERENCES MODELS(ID);
ALTER TABLE `ITEMS`  ADD CONSTRAINT FOREIGN KEY (STOCK_ID) REFERENCES STOCKS(ID);

INSERT INTO `ITEMS` (`COMMENT`, `MODEL_ID`, `PHOTO1`, `PHOTO2`, `PHOTO3`, `STATUS`, `STOCK_ID`) VALUES ('', '1', '', '', '', '', '1');
INSERT INTO `ITEMS` (`COMMENT`, `MODEL_ID`, `PHOTO1`, `PHOTO2`, `PHOTO3`, `STATUS`, `STOCK_ID`) VALUES ('', '1', '', '', '', '', '1');
INSERT INTO `ITEMS` (`COMMENT`, `MODEL_ID`, `PHOTO1`, `PHOTO2`, `PHOTO3`, `STATUS`, `STOCK_ID`) VALUES ('', '1', '', '', '', '', '1');
INSERT INTO `ITEMS` (`COMMENT`, `MODEL_ID`, `PHOTO1`, `PHOTO2`, `PHOTO3`, `STATUS`, `STOCK_ID`) VALUES ('', '2', '', '', '', '', '1');
INSERT INTO `ITEMS` (`COMMENT`, `MODEL_ID`, `PHOTO1`, `PHOTO2`, `PHOTO3`, `STATUS`, `STOCK_ID`) VALUES ('', '2', '', '', '', '', '1');
INSERT INTO `ITEMS` (`COMMENT`, `MODEL_ID`, `PHOTO1`, `PHOTO2`, `PHOTO3`, `STATUS`, `STOCK_ID`) VALUES ('', '2', '', '', '', '', '1');
INSERT INTO `ITEMS` (`COMMENT`, `MODEL_ID`, `PHOTO1`, `PHOTO2`, `PHOTO3`, `STATUS`, `STOCK_ID`) VALUES ('', '3', '', '', '', '', '1');
INSERT INTO `ITEMS` (`COMMENT`, `MODEL_ID`, `PHOTO1`, `PHOTO2`, `PHOTO3`, `STATUS`, `STOCK_ID`) VALUES ('', '3', '', '', '', '', '1');
INSERT INTO `ITEMS` (`COMMENT`, `MODEL_ID`, `PHOTO1`, `PHOTO2`, `PHOTO3`, `STATUS`, `STOCK_ID`) VALUES ('', '3', '', '', '', '', '1');

DROP TABLE IF EXISTS `ORDERS`;
CREATE TABLE `ORDERS` (
  `ID` int(11) NOT NULL,
  `STATUS_ID` int(11) NOT NULL,
  `COMMENT` text,
  `CLIENT_ID` int(11) NOT NULL,
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `BEGIN` datetime NOT NULL,
  `END` datetime NOT NULL,
  `DELIVERY_ADDRESS_TO` varchar(1000),
  `DELIVERY_ADDRESS_FROM` varchar(1000),
  `TOTAL_AMOUNT` float NOT NULL,
  `TOTAL_DEPOSIT` float NOT NULL,
  `GIVER_ID` int(11) NOT NULL COMMENT 'сотрудник, который выдает',
  `TAKER_ID` int(11) NOT NULL COMMENT 'сотрудник, который забирает',
  `GIVE_STOCK_ID` int(11) NOT NULL COMMENT 'склад выдачи',
  `TAKE_STOCK_ID` int(11) NOT NULL COMMENT 'склад, на который принимаем'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Таблица заказов';
ALTER TABLE `ORDERS`  ADD PRIMARY KEY (`ID`);
ALTER TABLE `ORDERS`  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
ALTER TABLE `ORDERS`  ADD CONSTRAINT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID);
ALTER TABLE `ORDERS`  ADD CONSTRAINT FOREIGN KEY (GIVER_ID) REFERENCES EMPLOYEES(ID);
ALTER TABLE `ORDERS`  ADD CONSTRAINT FOREIGN KEY (TAKER_ID) REFERENCES EMPLOYEES(ID);
ALTER TABLE `ORDERS`  ADD CONSTRAINT FOREIGN KEY (GIVE_STOCK_ID) REFERENCES STOCKS(ID);
ALTER TABLE `ORDERS`  ADD CONSTRAINT FOREIGN KEY (TAKE_STOCK_ID) REFERENCES STOCKS(ID);
ALTER TABLE `ORDERS`  ADD CONSTRAINT FOREIGN KEY (STATUS_ID) REFERENCES STATUS(ID);

DROP TABLE IF EXISTS `ITEMS_TO_ORDERS`;
CREATE TABLE `ITEMS_TO_ORDERS` (
  `ORDER_ID` int(11) NOT NULL,
  `ITEM_ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `ITEMS_TO_ORDERS`  ADD CONSTRAINT FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID);
ALTER TABLE `ITEMS_TO_ORDERS`  ADD CONSTRAINT FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID);

DROP TABLE IF EXISTS `MODELS_TO_ORDERS`;
CREATE TABLE `MODELS_TO_ORDERS` (
  `ORDER_ID` int(11) NOT NULL,
  `MODEL_ID` int(11) NOT NULL,
  `COUNT` int(11) NOT NULL,
  `PRICE` float NOT NULL,
  `DEPOSIT` float NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `MODELS_TO_ORDERS`  ADD CONSTRAINT FOREIGN KEY (MODEL_ID) REFERENCES MODELS(ID);
ALTER TABLE `MODELS_TO_ORDERS`  ADD CONSTRAINT FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID);

DROP TABLE IF EXISTS `MOVEMENTS`;
CREATE TABLE `MOVEMENTS` (
  `ID` int(11) NOT NULL,
  `FROM_STOCK_ID` int(11) NOT NULL,
  `TO_STOCK_ID` int(11) NOT NULL,
  `ITEM_ID` int(11) NOT NULL,
  `CREATED` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENT` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `MOVEMENTS`  ADD PRIMARY KEY (`ID`);
ALTER TABLE `MOVEMENTS`  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
ALTER TABLE `MOVEMENTS`  ADD CONSTRAINT FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID);
ALTER TABLE `MOVEMENTS`  ADD CONSTRAINT FOREIGN KEY (FROM_STOCK_ID) REFERENCES STOCKS(ID);
ALTER TABLE `MOVEMENTS`  ADD CONSTRAINT FOREIGN KEY (TO_STOCK_ID) REFERENCES STOCKS(ID);


SET foreign_key_checks = 1;